### ISSUE TITLE
please update gnome-shell-impatience to be compatible with gnome 47 

### ISSUE THREAD

**Issue by githlacker** [timbertson/gnome-shell-impatience#39]

**Comment by bulletmark** [comment]
Impatience is always slow to get updated after a new GNOME release but you can eliminate this frustration by setting `GNOME_SHELL_SLOWDOWN_FACTOR=0.5` in `/etc/environment`. Then there is no need for this extension.

**Comment by timbertson** [comment]
You're not wrong, I lag behind gnome releases because I don't have the energy to keep running prereleases / update immediately. I understand why they did it, but I wish you could mark an extension as compatible by default so we don't have to go through this every release.

The irony is this time I actually did have it ready thanks to #38 , I just hadn't uploaded the zip to extensions.gnome.org yet 🤦 . Uploaded now, it should be auto-approved shortly.
