### ISSUE TITLE
setting speed factor through gsettings

### ISSUE THREAD

**Issue by ghost** [timbertson/gnome-shell-impatience#8]
Hi Tim,

it would be nice if one could set the speed factor through gsettings to ease mass deployment.

Regards,
Daniel

**Comment by gfxmonk** [comment]
If #7 gets fixed, do you need anything else to enable this? I'm assuming you have some way of setting system-wide gsettings already?

**Comment by daniel-baumann** [comment]
#7 and #8 are two unrelated things.

#7 is about being able to deploy the extension properly (files in proper locations if installed system wide).

#8 is about being able, regardless if it's system-wide or locally installed, to be able to control/set the actual value non-interactively through gsettings, rather than through the GUI.

**Comment by gfxmonk** [comment]
Thanks for clarifying. I believe the only thing stopping you from changing settings with gsettings is that you need the appropriate entry in $XDG_DATA_DIRS. There's nothing I can do to make that happen for you system-wide if you've installed the extension locally, other than provide instructions on setting up $XDG_DATA_DIRS (which I'd imagine most people needing to do this would already know how to do anyway).
